[2024-07-14T07:48:36.897+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T07:48:37.138+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-07-14T07:48:06.070746+00:00 [queued]>
[2024-07-14T07:48:37.181+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-07-14T07:48:06.070746+00:00 [queued]>
[2024-07-14T07:48:37.183+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-14T07:48:37.290+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_wikipedia_data> on 2024-07-14 07:48:06.070746+00:00
[2024-07-14T07:48:37.312+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'transform_wikipedia_data', 'manual__2024-07-14T07:48:06.070746+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_flow.py', '--cfg-path', '/tmp/tmprkbuqkw8']
[2024-07-14T07:48:37.326+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask transform_wikipedia_data
[2024-07-14T07:48:37.334+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=769) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T07:48:37.346+0000] {standard_task_runner.py:63} INFO - Started process 773 to run task
[2024-07-14T07:48:37.543+0000] {task_command.py:426} INFO - Running <TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-07-14T07:48:06.070746+00:00 [running]> on host e9db26b4e04f
[2024-07-14T07:48:38.015+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ayush Goswami' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='transform_wikipedia_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T07:48:06.070746+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-14T07:48:06.070746+00:00'
[2024-07-14T07:48:38.020+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T07:48:39.041+0000] {logging_mixin.py:188} INFO - data
[2024-07-14T07:48:39.083+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T07:48:39.084+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline/wikipedia_pipeline.py", line 73, in transform_wikipedia_data
    stadium_df['location']=stadium_df.apply(lambda x: get_lat_long(x["country"],x["stadium"]),axis=1)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 10034, in apply
    return op.apply().__finalize__(self, method="apply")
           ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 837, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 965, in apply_standard
    results, res_index = self.apply_series_generator()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 981, in apply_series_generator
    results[i] = self.func(v, *self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline/wikipedia_pipeline.py", line 73, in <lambda>
    stadium_df['location']=stadium_df.apply(lambda x: get_lat_long(x["country"],x["stadium"]),axis=1)
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline/wikipedia_pipeline.py", line 59, in get_lat_long
    from geopy.geocoders import Nominatim
ModuleNotFoundError: No module named 'geopy'
[2024-07-14T07:48:39.167+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=wikipedia_flow, task_id=transform_wikipedia_data, run_id=manual__2024-07-14T07:48:06.070746+00:00, execution_date=20240714T074806, start_date=20240714T074837, end_date=20240714T074839
[2024-07-14T07:48:39.267+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 11 for task transform_wikipedia_data (No module named 'geopy'; 773)
[2024-07-14T07:48:39.329+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-14T07:48:39.444+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T07:48:39.544+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
