[2024-06-19T07:58:49.751+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T07:58:49.862+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.write_wikipedia_data manual__2024-06-19T07:53:11.014737+00:00 [queued]>
[2024-06-19T07:58:49.904+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.write_wikipedia_data manual__2024-06-19T07:53:11.014737+00:00 [queued]>
[2024-06-19T07:58:49.906+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-19T07:58:50.067+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): write_wikipedia_data> on 2024-06-19 07:53:11.014737+00:00
[2024-06-19T07:58:50.101+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'write_wikipedia_data', 'manual__2024-06-19T07:53:11.014737+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_flow.py', '--cfg-path', '/tmp/tmpmw1cp41k']
[2024-06-19T07:58:50.109+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask write_wikipedia_data
[2024-06-19T07:58:50.108+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2135) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-19T07:58:50.110+0000] {standard_task_runner.py:63} INFO - Started process 2137 to run task
[2024-06-19T07:58:50.386+0000] {task_command.py:426} INFO - Running <TaskInstance: wikipedia_flow.write_wikipedia_data manual__2024-06-19T07:53:11.014737+00:00 [running]> on host dd278de8866b
[2024-06-19T07:58:50.945+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ayush Goswami' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='write_wikipedia_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T07:53:11.014737+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-19T07:53:11.014737+00:00'
[2024-06-19T07:58:50.952+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T07:58:51.477+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T07:58:51.478+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline/wikipedia_pipeline.py", line 90, in write_wikipedia_data
    data.to_csv('data/'+filename,index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'data'
[2024-06-19T07:58:51.554+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=wikipedia_flow, task_id=write_wikipedia_data, run_id=manual__2024-06-19T07:53:11.014737+00:00, execution_date=20240619T075311, start_date=20240619T075849, end_date=20240619T075851
[2024-06-19T07:58:51.617+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 20 for task write_wikipedia_data (Cannot save file into a non-existent directory: 'data'; 2137)
[2024-06-19T07:58:51.640+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-19T07:58:51.675+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-19T07:58:51.696+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
