[2024-06-19T07:32:34.799+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T07:32:34.920+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-06-19T07:32:20.498564+00:00 [queued]>
[2024-06-19T07:32:34.989+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-06-19T07:32:20.498564+00:00 [queued]>
[2024-06-19T07:32:34.990+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-19T07:32:35.103+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_wikipedia_data> on 2024-06-19 07:32:20.498564+00:00
[2024-06-19T07:32:35.157+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'transform_wikipedia_data', 'manual__2024-06-19T07:32:20.498564+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_flow.py', '--cfg-path', '/tmp/tmp9iyd_bma']
[2024-06-19T07:32:35.190+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask transform_wikipedia_data
[2024-06-19T07:32:35.193+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1246) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-19T07:32:35.207+0000] {standard_task_runner.py:63} INFO - Started process 1248 to run task
[2024-06-19T07:32:35.665+0000] {task_command.py:426} INFO - Running <TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-06-19T07:32:20.498564+00:00 [running]> on host dd278de8866b
[2024-06-19T07:32:36.417+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ayush Goswami' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='transform_wikipedia_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T07:32:20.498564+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-19T07:32:20.498564+00:00'
[2024-06-19T07:32:36.424+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T07:32:37.229+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T07:32:37.230+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline/wikipedia_pipeline.py", line 69, in transform_wikipedia_data
    stadium_df['location']=stadium_df.apply(lambda x: get_lat_long(x["stadium"],x["country"],x["city"]),axis=1)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 10034, in apply
    return op.apply().__finalize__(self, method="apply")
           ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 837, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 965, in apply_standard
    results, res_index = self.apply_series_generator()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 981, in apply_series_generator
    results[i] = self.func(v, *self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline/wikipedia_pipeline.py", line 69, in <lambda>
    stadium_df['location']=stadium_df.apply(lambda x: get_lat_long(x["stadium"],x["country"],x["city"]),axis=1)
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline/wikipedia_pipeline.py", line 58, in get_lat_long
    location = geolocator.geocode({stadium},{city},{country})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Nominatim.geocode() takes 2 positional arguments but 4 were given
[2024-06-19T07:32:37.327+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=wikipedia_flow, task_id=transform_wikipedia_data, run_id=manual__2024-06-19T07:32:20.498564+00:00, execution_date=20240619T073220, start_date=20240619T073234, end_date=20240619T073237
[2024-06-19T07:32:37.383+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 11 for task transform_wikipedia_data (Nominatim.geocode() takes 2 positional arguments but 4 were given; 1248)
[2024-06-19T07:32:37.412+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-19T07:32:37.481+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-19T07:32:37.536+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
