[2024-06-16T04:01:44.917+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: example_bash_operator.this_will_skip scheduled__2024-06-15T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
